index:
  path: /
  controller: App\Controller\DefaultController::index
currency_saves:
  path: /saving/currency
  controller: App\Controller\SavingCurrencyController::index
dashboard:
  path: /admin
  controller: App\Controller\Admin\DashboardController::index
